version: "3"

services:
    hometest_backend:
        build:
            context: .
        ports:
            - 3000:3000
        cap_add:
            - SYS_ADMIN
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgres://hometest_user:123456@hometest_db:5432/hometest_db
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=123456
        volumes:
            - ./download:/home/node/app/download
            - ./html-source:/home/node/app/html-source
            - ./logs:/home/node/app/logs
            # - ./dbus/run.sh:/etc/init/run.sh
            
        networks:
            - hometest_backend_network
        links:
            - hometest_db
            - redis
        depends_on:
            - hometest_db
            - redis
        tty: true
    hometest_db:
        image: 'bitnami/postgresql:11'
        ports:
            - 5432:5432
        restart: always
        volumes:
            - postgresql_data:/bitnami/postgresql            
        environment:
            - POSTGRESQL_PASSWORD=123456
            - POSTGRESQL_USERNAME=hometest_user
            - POSTGRESQL_DATABASE=hometest_db
        networks:
            - hometest_backend_network
    redis:
        image: docker.io/bitnami/redis:6.2
        restart: always
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            #- ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PASSWORD=123456
            # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/bitnami/redis/data'
        networks:
            - hometest_backend_network
volumes:
    postgresql_data:
        driver: local
    redis_data:
        driver: local
networks:
    hometest_backend_network: