export const isImage = {
  '.jpg': true,
  '.jpeg': true,
  '.jpe': true,
  '.jif': true,
  '.jfif': true,
  '.jfi': true,
  '.png': true,
  '.gif': true,
  '.webp': true,
  '.tiff': true,
  '.tif': true,
  '.psd': true,
  '.raw': true,
  '.arw': true,
  '.cr2': true,
  '.nrw': true,
  '.k25': true,
  '.bmp': true,
  '.dib': true,
  '.heif': true,
  '.heic': true,
  '.ind': true,
  '.indd': true,
  '.indt': true,
  '.jp2': true,
  '.j2k': true,
  '.jpf': true,
  '.jpx': true,
  '.jpm': true,
  '.mj2': true,
  '.svg': true,
  '.svgz': true,
  '.ai': true,
  '.eps': true,
  '.pdf': true,
};

export const isVideo = {
  '.MPG': true,
  '.MP2': true,
  '.MPEG': true,
  '.MPE': true,
  '.MPV': true,
  '.OGG': true,
  '.MP4': true,
  '.M4P': true,
  '.M4V': true,
  '.AVI': true,
  '.WMV': true,
  '.MOV': true,
  '.QT': true,
  '.FLV': true,
  '.SWF': true,
  '.WEBM': true,
};
